# Generated by Django 5.1.7 on 2025-04-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stagingdata",
            name="status",
        ),
        migrations.AlterField(
            model_name="stagingdata",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
