# Generated by Django 5.1.7 on 2025-04-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0002_remove_stagingdata_status_alter_stagingdata_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stagingdata",
            name="raw_data",
        ),
        migrations.AddField(
            model_name="stagingdata",
            name="table_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="stagingdata",
            name="source_type",
            field=models.CharField(max_length=20),
        ),
    ]
