# Generated by Django 5.1.7 on 2025-04-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ingestion",
            "0003_remove_stagingdata_raw_data_stagingdata_table_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="stagingdata",
            name="source_type",
            field=models.CharField(
                choices=[("CSV", "CSV"), ("PostgreSQL", "PostgreSQL")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="stagingdata",
            name="table_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
