# Generated by Django 5.1.6 on 2025-02-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StagingData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("raw_data", models.JSONField()),
                ("source_type", models.CharField(max_length=50)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
